---

- name: Install Docker repository dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common

- name: Add Docker Debian repository key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    id: 0EBFCD88
    state: present

- name: Set Docker Debian repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install docker
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce
      - docker-compose-plugin
      - python3-docker

...